language: python
python:
  - "3.6"
before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=3.6
  - source activate test-environment
  - conda install -q -c conda-forge -c cmutel -c haasad bw2data bw2calc pytest pytest-cov numpy scipy stats_arrays peewee wrapt eight future=0.16.0
  - echo $(python --version)
install: "python setup.py develop"
script:
  - pwd; pytest --cov=presamples
after_success:
  - pip install python-coveralls; coveralls
